This is my first Notebook and data analysis project. If you spot any errors or problems, please let me know. Thank You. 

------------------------------------------------------------------------------------------------------------------------------------
Cyclistic company data analysis
5/5/2026
Bunsiness Task: To find new offers to make to casual riders to convert them to a memebership. 
------------------------------------------------------------------------------------------------------------------------------------

Description of data sources used:
Pulled biking data from the year 2025. 
This data was made public under this license. 
https://divvybikes.com/data-license-agreement
This Link is where the data is stored and i got 
https://divvy-tripdata.s3.amazonaws.com/index.html

In [1]:
import pandas as pd

In [ ]:
#Importing and combining data
df1 = pd.read_csv(r"202501-divvy-tripdata.csv")
df2 = pd.read_csv(r"202502-divvy-tripdata.csv ")
df3 = pd.read_csv(r"202503-divvy-tripdata.csv")
df4 = pd.read_csv(r"202504-divvy-tripdata.csv")
df5 = pd.read_csv(r"202505-divvy-tripdata.csv")
df6 = pd.read_csv(r"202506-divvy-tripdata.csv")
df7 = pd.read_csv(r"202507-divvy-tripdata.csv")
df8 = pd.read_csv(r"202508-divvy-tripdata.csv")
df9 = pd.read_csv(r"202509-divvy-tripdata.csv")
df10 = pd.read_csv(r"202510-divvy-tripdata.csv")
df11 = pd.read_csv(r"202511-divvy-tripdata.csv")
df12 = pd.read_csv(r"202512-divvy-tripdata.csv")

In [3]:
# checking sizes of each data frame and if anything sticks out. 
df_list = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12]
n = 0
for i in df_list:
    n += 1
    print(f"\n df{n}-------------------------------------------------------------------------------------")
    print(f"{i.info()}")
n = 0

 df1-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 138689 entries, 0 to 138688
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             138689 non-null  str
 1   rideable_type       138689 non-null  str
 2   started_at          138689 non-null  str
 3   ended_at            138689 non-null  str
 4   start_station_name  115837 non-null  str
 5   start_station_id    115837 non-null  str
 6   end_station_name    114616 non-null  str
 7   end_station_id      114616 non-null  str
 8   start_lat           138689 non-null  float64
 9   start_lng           138689 non-null  float64
 10  end_lat             138628 non-null  float64
 11  end_lng             138628 non-null  float64
 12  member_casual       138689 non-null  str
dtypes: float64(4), str(9)
memory usage: 13.8 MB
None

 df2-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 151880 entries, 0 to 151879
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             151880 non-null  str
 1   rideable_type       151880 non-null  str
 2   started_at          151880 non-null  str
 3   ended_at            151880 non-null  str
 4   start_station_name  125952 non-null  str
 5   start_station_id    125952 non-null  str
 6   end_station_name    124631 non-null  str
 7   end_station_id      124631 non-null  str
 8   start_lat           151880 non-null  float64
 9   start_lng           151880 non-null  float64
 10  end_lat             151823 non-null  float64
 11  end_lng             151823 non-null  float64
 12  member_casual       151880 non-null  str
dtypes: float64(4), str(9)
memory usage: 15.1 MB
None

 df3-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 298155 entries, 0 to 298154
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             298155 non-null  str
 1   rideable_type       298155 non-null  str
 2   started_at          298155 non-null  str
 3   ended_at            298155 non-null  str
 4   start_station_name  242818 non-null  str
 5   start_station_id    242818 non-null  str
 6   end_station_name    240171 non-null  str
 7   end_station_id      240171 non-null  str
 8   start_lat           298155 non-null  float64
 9   start_lng           298155 non-null  float64
 10  end_lat             297914 non-null  float64
 11  end_lng             297914 non-null  float64
 12  member_casual       298155 non-null  str
dtypes: float64(4), str(9)
memory usage: 29.6 MB
None

 df4-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 371341 entries, 0 to 371340
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             371341 non-null  str
 1   rideable_type       371341 non-null  str
 2   started_at          371341 non-null  str
 3   ended_at            371341 non-null  str
 4   start_station_name  300145 non-null  str
 5   start_station_id    300145 non-null  str
 6   end_station_name    297706 non-null  str
 7   end_station_id      297706 non-null  str
 8   start_lat           371341 non-null  float64
 9   start_lng           371341 non-null  float64
 10  end_lat             371052 non-null  float64
 11  end_lng             371052 non-null  float64
 12  member_casual       371341 non-null  str
dtypes: float64(4), str(9)
memory usage: 36.8 MB
None

 df5-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 502456 entries, 0 to 502455
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             502456 non-null  str
 1   rideable_type       502456 non-null  str
 2   started_at          502456 non-null  str
 3   ended_at            502456 non-null  str
 4   start_station_name  399096 non-null  str
 5   start_station_id    399096 non-null  str
 6   end_station_name    395020 non-null  str
 7   end_station_id      395020 non-null  str
 8   start_lat           502456 non-null  float64
 9   start_lng           502456 non-null  float64
 10  end_lat             501905 non-null  float64
 11  end_lng             501905 non-null  float64
 12  member_casual       502456 non-null  str
dtypes: float64(4), str(9)
memory usage: 49.8 MB
None

 df6-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 678904 entries, 0 to 678903
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             678904 non-null  str
 1   rideable_type       678904 non-null  str
 2   started_at          678904 non-null  str
 3   ended_at            678904 non-null  str
 4   start_station_name  528000 non-null  str
 5   start_station_id    528000 non-null  str
 6   end_station_name    522132 non-null  str
 7   end_station_id      522132 non-null  str
 8   start_lat           678904 non-null  float64
 9   start_lng           678904 non-null  float64
 10  end_lat             677916 non-null  float64
 11  end_lng             677916 non-null  float64
 12  member_casual       678904 non-null  str
dtypes: float64(4), str(9)
memory usage: 67.3 MB
None

 df7-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 763432 entries, 0 to 763431
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             763432 non-null  str
 1   rideable_type       763432 non-null  str
 2   started_at          763432 non-null  str
 3   ended_at            763432 non-null  str
 4   start_station_name  589903 non-null  str
 5   start_station_id    589903 non-null  str
 6   end_station_name    581926 non-null  str
 7   end_station_id      581926 non-null  str
 8   start_lat           763432 non-null  float64
 9   start_lng           763432 non-null  float64
 10  end_lat             762461 non-null  float64
 11  end_lng             762461 non-null  float64
 12  member_casual       763432 non-null  str
dtypes: float64(4), str(9)
memory usage: 75.7 MB
None

 df8-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 790177 entries, 0 to 790176
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             790177 non-null  str
 1   rideable_type       790177 non-null  str
 2   started_at          790177 non-null  str
 3   ended_at            790177 non-null  str
 4   start_station_name  613056 non-null  str
 5   start_station_id    613056 non-null  str
 6   end_station_name    605417 non-null  str
 7   end_station_id      605417 non-null  str
 8   start_lat           790177 non-null  float64
 9   start_lng           790177 non-null  float64
 10  end_lat             789484 non-null  float64
 11  end_lng             789484 non-null  float64
 12  member_casual       790177 non-null  str
dtypes: float64(4), str(9)
memory usage: 78.4 MB
None

 df9-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 714759 entries, 0 to 714758
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             714759 non-null  str
 1   rideable_type       714759 non-null  str
 2   started_at          714759 non-null  str
 3   ended_at            714759 non-null  str
 4   start_station_name  558498 non-null  str
 5   start_station_id    558498 non-null  str
 6   end_station_name    550276 non-null  str
 7   end_station_id      550276 non-null  str
 8   start_lat           714759 non-null  float64
 9   start_lng           714759 non-null  float64
 10  end_lat             714140 non-null  float64
 11  end_lng             714140 non-null  float64
 12  member_casual       714759 non-null  str
dtypes: float64(4), str(9)
memory usage: 70.9 MB
None

 df10-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 646039 entries, 0 to 646038
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             646039 non-null  str
 1   rideable_type       646039 non-null  str
 2   started_at          646039 non-null  str
 3   ended_at            646039 non-null  str
 4   start_station_name  501060 non-null  str
 5   start_station_id    501060 non-null  str
 6   end_station_name    492573 non-null  str
 7   end_station_id      492573 non-null  str
 8   start_lat           646039 non-null  float64
 9   start_lng           646039 non-null  float64
 10  end_lat             645453 non-null  float64
 11  end_lng             645453 non-null  float64
 12  member_casual       646039 non-null  str
dtypes: float64(4), str(9)
memory usage: 64.1 MB
None

 df11-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 356628 entries, 0 to 356627
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             356628 non-null  str
 1   rideable_type       356628 non-null  str
 2   started_at          356628 non-null  str
 3   ended_at            356628 non-null  str
 4   start_station_name  280348 non-null  str
 5   start_station_id    280348 non-null  str
 6   end_station_name    274732 non-null  str
 7   end_station_id      274732 non-null  str
 8   start_lat           356628 non-null  float64
 9   start_lng           356628 non-null  float64
 10  end_lat             356271 non-null  float64
 11  end_lng             356271 non-null  float64
 12  member_casual       356628 non-null  str
dtypes: float64(4), str(9)
memory usage: 35.4 MB
None

 df12-------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 140534 entries, 0 to 140533
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             140534 non-null  str
 1   rideable_type       140534 non-null  str
 2   started_at          140534 non-null  str
 3   ended_at            140534 non-null  str
 4   start_station_name  113608 non-null  str
 5   start_station_id    113608 non-null  str
 6   end_station_name    110489 non-null  str
 7   end_station_id      110489 non-null  str
 8   start_lat           140534 non-null  float64
 9   start_lng           140534 non-null  float64
 10  end_lat             140412 non-null  float64
 11  end_lng             140412 non-null  float64
 12  member_casual       140534 non-null  str
dtypes: float64(4), str(9)
memory usage: 13.9 MB
None

In [4]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
140529,53202484E8371237,electric_bike,2025-12-19 13:43:41.793,2025-12-19 13:54:07.779,Sheffield Ave & Kingsbury St,CHI02023,Halsted St & Melrose St,CHI02162,41.910522,-87.653106,41.941120,-87.649070,member
140530,3582BF76707AB2ED,classic_bike,2025-12-27 12:43:48.446,2025-12-27 12:52:45.141,Larrabee St & Webster Ave,CHI00454,Halsted St & Melrose St,CHI02162,41.921822,-87.644140,41.941120,-87.649070,member
140531,B12D92DF229EFA41,electric_bike,2025-12-20 01:12:39.053,2025-12-20 01:18:55.928,Clarendon Ave & Junior Ter,CHI00395,Halsted St & Melrose St,CHI02162,41.961004,-87.649603,41.941120,-87.649070,casual
140532,04D5C6C11909ECAE,electric_bike,2025-12-08 16:46:37.496,2025-12-08 16:58:32.762,Lincoln Ave & Waveland Ave,CHI00446,Halsted St & Wrightwood Ave,CHI00504,41.948797,-87.675278,41.929143,-87.649077,member
140533,D2CF23B6D79232B6,classic_bike,2025-12-20 13:08:27.589,2025-12-20 13:13:54.815,Larrabee St & Webster Ave,CHI00454,Halsted St & Wrightwood Ave,CHI00504,41.921822,-87.644140,41.929143,-87.649077,member

checking data frame and cleaning

In [5]:
#checking for null values

print("\nMissing values for df:")
print(df.isnull().sum())

Missing values for df:
ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1184673
start_station_id      1184673
end_station_name      1243305
end_station_id        1243305
start_lat                   0
start_lng                   0
end_lat                  5535
end_lng                  5535
member_casual               0
dtype: int64

In [6]:
#chekcing for duplicates values

print("\nDuplicate values for df:")
print(df.duplicated().sum())

Duplicate values for df:
0

In [7]:
#finding distribution of df's missing values
for i in df_list:
    n += 1
    print(f"df{n}------------------------------------------------------------------------------------------")
    print(i.isnull().sum())
    print(f"df{n} WITH values ------------------------------------------------------------------------------------------")
    print(i.notnull().sum())
n = 0

df1------------------------------------------------------------------------------------------
ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    22852
start_station_id      22852
end_station_name      24073
end_station_id        24073
start_lat                 0
start_lng                 0
end_lat                  61
end_lng                  61
member_casual             0
dtype: int64
df1 WITH values ------------------------------------------------------------------------------------------
ride_id               138689
rideable_type         138689
started_at            138689
ended_at              138689
start_station_name    115837
start_station_id      115837
end_station_name      114616
end_station_id        114616
start_lat             138689
start_lng             138689
end_lat               138628
end_lng               138628
member_casual         138689
dtype: int64
df2------------------------------------------------------------------------------------------
ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    25928
start_station_id      25928
end_station_name      27249
end_station_id        27249
start_lat                 0
start_lng                 0
end_lat                  57
end_lng                  57
member_casual             0
dtype: int64
df2 WITH values ------------------------------------------------------------------------------------------
ride_id               151880
rideable_type         151880
started_at            151880
ended_at              151880
start_station_name    125952
start_station_id      125952
end_station_name      124631
end_station_id        124631
start_lat             151880
start_lng             151880
end_lat               151823
end_lng               151823
member_casual         151880
dtype: int64
df3------------------------------------------------------------------------------------------
ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    55337
start_station_id      55337
end_station_name      57984
end_station_id        57984
start_lat                 0
start_lng                 0
end_lat                 241
end_lng                 241
member_casual             0
dtype: int64
df3 WITH values ------------------------------------------------------------------------------------------
ride_id               298155
rideable_type         298155
started_at            298155
ended_at              298155
start_station_name    242818
start_station_id      242818
end_station_name      240171
end_station_id        240171
start_lat             298155
start_lng             298155
end_lat               297914
end_lng               297914
member_casual         298155
dtype: int64
df4------------------------------------------------------------------------------------------
ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    71196
start_station_id      71196
end_station_name      73635
end_station_id        73635
start_lat                 0
start_lng                 0
end_lat                 289
end_lng                 289
member_casual             0
dtype: int64
df4 WITH values ------------------------------------------------------------------------------------------
ride_id               371341
rideable_type         371341
started_at            371341
ended_at              371341
start_station_name    300145
start_station_id      300145
end_station_name      297706
end_station_id        297706
start_lat             371341
start_lng             371341
end_lat               371052
end_lng               371052
member_casual         371341
dtype: int64
df5------------------------------------------------------------------------------------------
ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    103360
start_station_id      103360
end_station_name      107436
end_station_id        107436
start_lat                  0
start_lng                  0
end_lat                  551
end_lng                  551
member_casual              0
dtype: int64
df5 WITH values ------------------------------------------------------------------------------------------
ride_id               502456
rideable_type         502456
started_at            502456
ended_at              502456
start_station_name    399096
start_station_id      399096
end_station_name      395020
end_station_id        395020
start_lat             502456
start_lng             502456
end_lat               501905
end_lng               501905
member_casual         502456
dtype: int64
df6------------------------------------------------------------------------------------------
ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    150904
start_station_id      150904
end_station_name      156772
end_station_id        156772
start_lat                  0
start_lng                  0
end_lat                  988
end_lng                  988
member_casual              0
dtype: int64
df6 WITH values ------------------------------------------------------------------------------------------
ride_id               678904
rideable_type         678904
started_at            678904
ended_at              678904
start_station_name    528000
start_station_id      528000
end_station_name      522132
end_station_id        522132
start_lat             678904
start_lng             678904
end_lat               677916
end_lng               677916
member_casual         678904
dtype: int64
df7------------------------------------------------------------------------------------------
ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    173529
start_station_id      173529
end_station_name      181506
end_station_id        181506
start_lat                  0
start_lng                  0
end_lat                  971
end_lng                  971
member_casual              0
dtype: int64
df7 WITH values ------------------------------------------------------------------------------------------
ride_id               763432
rideable_type         763432
started_at            763432
ended_at              763432
start_station_name    589903
start_station_id      589903
end_station_name      581926
end_station_id        581926
start_lat             763432
start_lng             763432
end_lat               762461
end_lng               762461
member_casual         763432
dtype: int64
df8------------------------------------------------------------------------------------------
ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    177121
start_station_id      177121
end_station_name      184760
end_station_id        184760
start_lat                  0
start_lng                  0
end_lat                  693
end_lng                  693
member_casual              0
dtype: int64
df8 WITH values ------------------------------------------------------------------------------------------
ride_id               790177
rideable_type         790177
started_at            790177
ended_at              790177
start_station_name    613056
start_station_id      613056
end_station_name      605417
end_station_id        605417
start_lat             790177
start_lng             790177
end_lat               789484
end_lng               789484
member_casual         790177
dtype: int64
df9------------------------------------------------------------------------------------------
ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    156261
start_station_id      156261
end_station_name      164483
end_station_id        164483
start_lat                  0
start_lng                  0
end_lat                  619
end_lng                  619
member_casual              0
dtype: int64
df9 WITH values ------------------------------------------------------------------------------------------
ride_id               714759
rideable_type         714759
started_at            714759
ended_at              714759
start_station_name    558498
start_station_id      558498
end_station_name      550276
end_station_id        550276
start_lat             714759
start_lng             714759
end_lat               714140
end_lng               714140
member_casual         714759
dtype: int64
df10------------------------------------------------------------------------------------------
ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    144979
start_station_id      144979
end_station_name      153466
end_station_id        153466
start_lat                  0
start_lng                  0
end_lat                  586
end_lng                  586
member_casual              0
dtype: int64
df10 WITH values ------------------------------------------------------------------------------------------
ride_id               646039
rideable_type         646039
started_at            646039
ended_at              646039
start_station_name    501060
start_station_id      501060
end_station_name      492573
end_station_id        492573
start_lat             646039
start_lng             646039
end_lat               645453
end_lng               645453
member_casual         646039
dtype: int64
df11------------------------------------------------------------------------------------------
ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    76280
start_station_id      76280
end_station_name      81896
end_station_id        81896
start_lat                 0
start_lng                 0
end_lat                 357
end_lng                 357
member_casual             0
dtype: int64
df11 WITH values ------------------------------------------------------------------------------------------
ride_id               356628
rideable_type         356628
started_at            356628
ended_at              356628
start_station_name    280348
start_station_id      280348
end_station_name      274732
end_station_id        274732
start_lat             356628
start_lng             356628
end_lat               356271
end_lng               356271
member_casual         356628
dtype: int64
df12------------------------------------------------------------------------------------------
ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    26926
start_station_id      26926
end_station_name      30045
end_station_id        30045
start_lat                 0
start_lng                 0
end_lat                 122
end_lng                 122
member_casual             0
dtype: int64
df12 WITH values ------------------------------------------------------------------------------------------
ride_id               140534
rideable_type         140534
started_at            140534
ended_at              140534
start_station_name    113608
start_station_id      113608
end_station_name      110489
end_station_id        110489
start_lat             140534
start_lng             140534
end_lat               140412
end_lng               140412
member_casual         140534
dtype: int64

Decided not drop rows with null's since they still had usful data. 
Like making a column form the "started_at" and "ended_at" columns.

In [ ]:
#Changing "started_at" and "ended_at" columns to Date data type from str

df["started_at"] = pd.to_datetime(df["started_at"])
df["ended_at"] = pd.to_datetime(df["ended_at"])
df.info()
print(f"\n---------------------------------------------------------------------------------------------------------------------------")
df.head(20)

<class 'pandas.DataFrame'>
Index: 5552994 entries, 0 to 140533
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          datetime64[us]
 3   ended_at            datetime64[us]
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      str
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: datetime64[us](2), float64(4), str(7)
memory usage: 593.1 MB

---------------------------------------------------------------------------------------------------------------------------

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
5,0B8DD16A9B77A1C7,electric_bike,2025-01-02 16:09:06.825,2025-01-02 16:10:55.784,Halsted St & 21st St,13162,Halsted St & 18th St,13099,41.853780,-87.646603,41.857506,-87.645991,member
6,65DD88D2EA5AA24A,electric_bike,2025-01-19 01:11:59.684,2025-01-19 01:15:54.187,Halsted St & Wrightwood Ave,TA1309000061,Southport Ave & Wrightwood Ave,TA1307000113,41.929143,-87.649077,41.928773,-87.663913,member
7,EAC4EE361C030130,electric_bike,2025-01-24 06:43:28.984,2025-01-24 07:01:38.943,Stave St & Armitage Ave,13266,Canal St & Madison St,13341,41.917741,-87.691392,41.882409,-87.639767,member
8,46267A54446162B5,electric_bike,2025-01-06 08:45:24.741,2025-01-06 08:50:20.458,Larrabee St & Kingsbury St,TA1306000009,Ogden Ave & Race Ave,13194,41.897764,-87.642884,41.891795,-87.658751,member
9,B5D4F9782121EA51,electric_bike,2025-01-01 16:56:36.927,2025-01-01 17:03:26.608,Albany Ave & Bloomingdale Ave,15655,Campbell Ave & Fullerton Ave,15648,41.914027,-87.705126,41.924632,-87.689307,member
10,3C1E48C025E88653,classic_bike,2024-12-31 23:52:33.890,2025-01-01 00:23:51.880,DuSable Lake Shore Dr & Wellington Ave,TA1307000041,Broadway & Barry Ave,13137,41.936688,-87.636829,41.937582,-87.644098,member
11,B157E60BBF2BA5F6,electric_bike,2025-01-04 17:23:29.630,2025-01-04 17:30:29.552,Clark St & Drummond Pl,TA1307000142,Clark St & Newport St,632,41.931248,-87.644336,41.944540,-87.654678,member
12,81AE62C30F86C0D2,classic_bike,2025-01-24 18:11:31.051,2025-01-24 18:17:05.253,Larrabee St & Kingsbury St,TA1306000009,Ogden Ave & Chicago Ave,TA1305000020,41.897764,-87.642884,41.896362,-87.654061,member
13,4978AFB4F96F17A6,classic_bike,2025-01-01 12:20:23.366,2025-01-01 12:28:29.458,Larrabee St & Kingsbury St,TA1306000009,State St & Pearson St,TA1307000061,41.897764,-87.642884,41.897448,-87.628722,member
14,1DCC4C0315A3B282,classic_bike,2025-01-06 13:52:47.368,2025-01-06 13:54:36.000,Calumet Ave & 18th St,13102,Calumet Ave & 18th St,13102,41.857618,-87.619411,41.857618,-87.619411,member
15,5B29C4C95B5320DA,electric_bike,2025-01-10 06:06:42.803,2025-01-10 06:11:43.893,Sheffield Ave & Webster Ave,TA1309000033,Halsted St & Clybourn Ave,331,41.921540,-87.653818,41.909668,-87.648128,member
16,18048F3531DAF576,electric_bike,2025-01-16 09:20:05.075,2025-01-16 09:23:32.385,Canal St & Jackson Blvd,13138,Halsted St & Polk St,TA1307000121,41.878125,-87.639968,41.871840,-87.646640,member
17,E2ACFA5C736376F6,electric_bike,2025-01-04 15:26:24.086,2025-01-04 15:42:18.743,California Ave & Fletcher St,15642,Kosciuszko Park,15643,41.938429,-87.698008,41.930585,-87.723777,member
18,B1810A3462EAA084,classic_bike,2025-01-17 08:13:24.981,2025-01-17 08:15:55.072,Hermitage Ave & Polk St,13080,Wood St & Taylor St (Temp),13285,41.871514,-87.669886,41.869265,-87.673731,member
19,461D6EC2A99BC110,classic_bike,2025-01-09 09:45:46.502,2025-01-09 10:05:59.273,Racine Ave & 15th St,13304,Stetson Ave & South Water St,TA1308000029,41.861267,-87.656625,41.886835,-87.622320,casual

In [9]:
#Adding Ride length column for every row. 
df["ride_length"] = (df["ended_at"] - df["started_at"]).dt.floor("s")
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,0 days 00:13:57
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,0 days 00:05:04
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,0 days 00:11:35
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,0 days 00:03:34
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,0 days 00:02:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140529,53202484E8371237,electric_bike,2025-12-19 13:43:41.793,2025-12-19 13:54:07.779,Sheffield Ave & Kingsbury St,CHI02023,Halsted St & Melrose St,CHI02162,41.910522,-87.653106,41.941120,-87.649070,member,0 days 00:10:25
140530,3582BF76707AB2ED,classic_bike,2025-12-27 12:43:48.446,2025-12-27 12:52:45.141,Larrabee St & Webster Ave,CHI00454,Halsted St & Melrose St,CHI02162,41.921822,-87.644140,41.941120,-87.649070,member,0 days 00:08:56
140531,B12D92DF229EFA41,electric_bike,2025-12-20 01:12:39.053,2025-12-20 01:18:55.928,Clarendon Ave & Junior Ter,CHI00395,Halsted St & Melrose St,CHI02162,41.961004,-87.649603,41.941120,-87.649070,casual,0 days 00:06:16
140532,04D5C6C11909ECAE,electric_bike,2025-12-08 16:46:37.496,2025-12-08 16:58:32.762,Lincoln Ave & Waveland Ave,CHI00446,Halsted St & Wrightwood Ave,CHI00504,41.948797,-87.675278,41.929143,-87.649077,member,0 days 00:11:55
140533,D2CF23B6D79232B6,classic_bike,2025-12-20 13:08:27.589,2025-12-20 13:13:54.815,Larrabee St & Webster Ave,CHI00454,Halsted St & Wrightwood Ave,CHI00504,41.921822,-87.644140,41.929143,-87.649077,member,0 days 00:05:27

In [10]:
import datetime

In [17]:
#added day of the week coulmn and month to data frame
df["day_of_week"] = df["started_at"].dt.strftime("%A")
df["mont_of_ride"] = df["started_at"].dt.strftime("%B")
df.head(20)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week,mont_of_ride
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,0 days 00:13:57,Tuesday,January
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,0 days 00:05:04,Saturday,January
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,0 days 00:11:35,Thursday,January
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,0 days 00:03:34,Thursday,January
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,0 days 00:02:34,Thursday,January
5,0B8DD16A9B77A1C7,electric_bike,2025-01-02 16:09:06.825,2025-01-02 16:10:55.784,Halsted St & 21st St,13162,Halsted St & 18th St,13099,41.853780,-87.646603,41.857506,-87.645991,member,0 days 00:01:48,Thursday,January
6,65DD88D2EA5AA24A,electric_bike,2025-01-19 01:11:59.684,2025-01-19 01:15:54.187,Halsted St & Wrightwood Ave,TA1309000061,Southport Ave & Wrightwood Ave,TA1307000113,41.929143,-87.649077,41.928773,-87.663913,member,0 days 00:03:54,Sunday,January
7,EAC4EE361C030130,electric_bike,2025-01-24 06:43:28.984,2025-01-24 07:01:38.943,Stave St & Armitage Ave,13266,Canal St & Madison St,13341,41.917741,-87.691392,41.882409,-87.639767,member,0 days 00:18:09,Friday,January
8,46267A54446162B5,electric_bike,2025-01-06 08:45:24.741,2025-01-06 08:50:20.458,Larrabee St & Kingsbury St,TA1306000009,Ogden Ave & Race Ave,13194,41.897764,-87.642884,41.891795,-87.658751,member,0 days 00:04:55,Monday,January
9,B5D4F9782121EA51,electric_bike,2025-01-01 16:56:36.927,2025-01-01 17:03:26.608,Albany Ave & Bloomingdale Ave,15655,Campbell Ave & Fullerton Ave,15648,41.914027,-87.705126,41.924632,-87.689307,member,0 days 00:06:49,Wednesday,January
10,3C1E48C025E88653,classic_bike,2024-12-31 23:52:33.890,2025-01-01 00:23:51.880,DuSable Lake Shore Dr & Wellington Ave,TA1307000041,Broadway & Barry Ave,13137,41.936688,-87.636829,41.937582,-87.644098,member,0 days 00:31:17,Tuesday,December
11,B157E60BBF2BA5F6,electric_bike,2025-01-04 17:23:29.630,2025-01-04 17:30:29.552,Clark St & Drummond Pl,TA1307000142,Clark St & Newport St,632,41.931248,-87.644336,41.944540,-87.654678,member,0 days 00:06:59,Saturday,January
12,81AE62C30F86C0D2,classic_bike,2025-01-24 18:11:31.051,2025-01-24 18:17:05.253,Larrabee St & Kingsbury St,TA1306000009,Ogden Ave & Chicago Ave,TA1305000020,41.897764,-87.642884,41.896362,-87.654061,member,0 days 00:05:34,Friday,January
13,4978AFB4F96F17A6,classic_bike,2025-01-01 12:20:23.366,2025-01-01 12:28:29.458,Larrabee St & Kingsbury St,TA1306000009,State St & Pearson St,TA1307000061,41.897764,-87.642884,41.897448,-87.628722,member,0 days 00:08:06,Wednesday,January
14,1DCC4C0315A3B282,classic_bike,2025-01-06 13:52:47.368,2025-01-06 13:54:36.000,Calumet Ave & 18th St,13102,Calumet Ave & 18th St,13102,41.857618,-87.619411,41.857618,-87.619411,member,0 days 00:01:48,Monday,January
15,5B29C4C95B5320DA,electric_bike,2025-01-10 06:06:42.803,2025-01-10 06:11:43.893,Sheffield Ave & Webster Ave,TA1309000033,Halsted St & Clybourn Ave,331,41.921540,-87.653818,41.909668,-87.648128,member,0 days 00:05:01,Friday,January
16,18048F3531DAF576,electric_bike,2025-01-16 09:20:05.075,2025-01-16 09:23:32.385,Canal St & Jackson Blvd,13138,Halsted St & Polk St,TA1307000121,41.878125,-87.639968,41.871840,-87.646640,member,0 days 00:03:27,Thursday,January
17,E2ACFA5C736376F6,electric_bike,2025-01-04 15:26:24.086,2025-01-04 15:42:18.743,California Ave & Fletcher St,15642,Kosciuszko Park,15643,41.938429,-87.698008,41.930585,-87.723777,member,0 days 00:15:54,Saturday,January
18,B1810A3462EAA084,classic_bike,2025-01-17 08:13:24.981,2025-01-17 08:15:55.072,Hermitage Ave & Polk St,13080,Wood St & Taylor St (Temp),13285,41.871514,-87.669886,41.869265,-87.673731,member,0 days 00:02:30,Friday,January
19,461D6EC2A99BC110,classic_bike,2025-01-09 09:45:46.502,2025-01-09 10:05:59.273,Racine Ave & 15th St,13304,Stetson Ave & South Water St,TA1308000029,41.861267,-87.656625,41.886835,-87.622320,casual,0 days 00:20:12,Thursday,January

In [18]:
#exporting to analysis notebook
df.to_csv("cleaned 2025 data.csv", index=False)